### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by PixelMut** [keephacking/ionic-essentials#2]
The package @keephacking/ionic-hide-onscroll is not found anymore
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@keephacking%2fionic-hide-onscroll - Not found

**Comment by keephacking** [comment]
Since this is a github package better you [check this](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages) to know more about github package installations.
